### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by mferuglio** [jammsen/docker-the-forest-dedicated-server#55]
Hi,

I used your docker-compose file.
I updated a bit my volumes.
I created new directories like you said in your Readme.
I generated a new token but serveur won't start.

Do you have any idea to help me?

docker-compose up logs :
```
theforest        | Checking if Wine is set in bashrc
theforest        | Setting up Wine in bashrc
theforest        | Setting up WineConfig and waiting 15 seconds
theforest        | linux32/
theforest        | linux32/libstdc++.so.6
theforest        | linux32/steamcmd
theforest        | steamcmd.sh
theforest        | steam.sh
theforest        | Redirecting stderr to '/root/Steam/logs/stderr.txt'
theforest        | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
theforest        | [  0%] Checking for available update...
theforest        | [  0%] Downloading update (0 of 90233 KB)...
theforest        | [  0%] Downloading update (4870 of 90233 KB)...
theforest        | [  5%] Downloading update (16275 of 90233 KB)...
theforest        | [ 18%] Downloading update (20439 of 90233 KB)...
theforest        | [ 22%] Downloading update (24998 of 90233 KB)...
theforest        | [ 27%] Downloading update (29166 of 90233 KB)...
theforest        | [ 32%] Downloading update (33309 of 90233 KB)...
theforest        | [ 36%] Downloading update (37449 of 90233 KB)...
theforest        | [ 41%] Downloading update (41608 of 90233 KB)...
theforest        | [ 46%] Downloading update (45723 of 90233 KB)...
theforest        | [ 50%] Downloading update (50249 of 90233 KB)...
theforest        | [ 55%] Downloading update (54384 of 90233 KB)...
theforest        | [ 60%] Downloading update (58550 of 90233 KB)...
theforest        | [ 64%] Downloading update (61705 of 90233 KB)...
theforest        | [ 68%] Downloading update (66296 of 90233 KB)...
theforest        | [ 73%] Downloading update (68359 of 90233 KB)...
theforest        | [ 75%] Downloading update (70443 of 90233 KB)...
theforest        | [ 78%] Downloading update (72521 of 90233 KB)...
theforest        | [ 80%] Downloading update (74575 of 90233 KB)...
theforest        | [ 82%] Downloading update (76861 of 90233 KB)...
theforest        | [ 85%] Downloading update (78922 of 90233 KB)...
theforest        | [ 87%] Downloading update (80995 of 90233 KB)...
theforest        | [ 89%] Downloading update (83052 of 90233 KB)...
theforest        | [ 92%] Downloading update (85341 of 90233 KB)...
theforest        | [ 94%] Downloading update (87390 of 90233 KB)...
theforest        | [ 96%] Downloading update (89463 of 90233 KB)...
theforest        | [ 99%] Downloading update (90233 of 90233 KB)...
theforest        | [100%] Download Complete.
theforest        | [----] Applying update...
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Installing update...
theforest        | [----] Cleaning up...
theforest        | [----] Failed to remove temporary unzip folder, continuing anyway
theforest        | [----] Update complete, launching...
theforest        | Redirecting stderr to '/root/Steam/logs/stderr.txt'
theforest        | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
theforest        | [  0%] Checking for available update...
theforest        | [  0%] Download Complete.
theforest        | [----] Verifying installation...
theforest        | [  0%] Downloading Update...
theforest        | [  0%] Checking for available update...
theforest        | [  0%] Download Complete.
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Extracting package...
theforest        | [----] Installing update...
theforest        | [----] Cleaning up...
theforest        | [----] Failed to remove temporary unzip folder, continuing anyway
theforest        | [----] Update complete, launching...
theforest        | Redirecting stderr to '/root/Steam/logs/stderr.txt'
theforest        | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
```

Docker-compose file :

```
  theforest:
    container_name: theforest
    image: jammsen/the-forest-dedicated-server:latest
    restart: always
    environment:
      SERVER_STEAM_ACCOUNT_TOKEN: 2565A8246369A6xxxxxxxxxxxxx
      ALWAYS_UPDATE_ON_START: 1
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - /data/theforest/steamcmd:/steamcmd
      - /data/theforest/game:/theforest
      - /data/theforest/winedata:/winedata

```

In advance,
Thank you.
